swipe:
        4:
                left:
                        command: "xdotool key ctrl+alt+Up"
                right:
                        command: "xdotool key ctrl+alt+Down"
                up:
                        command: "xdotool key ctrl+alt+Down"
                down:
                        command: "xdotool key ctrl+alt+Up"
pinch:
        in:
                command: "xdotool keydown ctrl click 4 keyup ctrl"
        out:
                command: "xdotool keydown ctrl click 5 keyup ctrl"
hold:
        4:
                command: "xdotool key super"
